.job_template: &job_definition
  stage: build
  except:
    - schedules

alpine-basic:
  <<: *job_definition
  image: alpine
  script:
    - apk update && apk add gcc bison musl-dev openssl-dev libcap-dev python3-dev
    - python3 ./waf configure --disable-doc --disable-manpage build
  tags:
    - gitlab-org

freebsd-11-basic:
  <<: *job_definition
  script:
    - python ./waf configure --disable-doc --disable-manpage build
  tags:
    - freebsd-11
  only:
    - branches@NTPsec/ntpsec

freebsd-12-basic:
  <<: *job_definition
  script:
    - python ./waf configure --disable-doc --disable-manpage build
  tags:
    - freebsd-12
  only:
    - branches@NTPsec/ntpsec

cross-build:
  <<: *job_definition
  script:
    - PYTHON_VERSION=2.7 PYTAG=cpython27 pyext_PATTERN="%s.so" PYTHON_LDFLAGS='-lpthread -ldl' ./waf configure --disable-doc --disable-manpage --cross-compiler=arm-linux-gnueabihf-gcc-5 --cross-cflags '-I/srv/arm-local/include -I/srv/arm-local/include/python2.7' --cross-ldflags '-L/srv/arm-local/lib' --pythondir=/srv/arm-local/lib/python2.7/dist-packages --pythonarchdir=/srv/arm-local/lib/python2.7/dist-packages build
  tags:
    - ubuntu-1604-lts
  only:
    - branches@NTPsec/ntpsec

macos-basic:
  <<: *job_definition
  script:
    - PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig python ./waf configure --disable-doc --disable-man build||echo
    - ls l* build/main/ntpd||echo
    - cat pylib/ntpc.py||echo
  tags:
    - macos
  only:
    - branches@NTPsec/ntpsec
